### PR TITLE
Create KeyCloack client while deploying OneZone

### PR DESCRIPTION
**Pull request by elegoff**
Related to https://github.com/SixSq/tasklist/issues/1172

### CODE REVIEW

**Comment by konstan** [comment]
1. Because the KC config URL is standard across KCs, I suggest

- add new RTP `realm_name` (required; no default)
- change RPT `hn-fedid-url` to only be the base URL with default https://fed-id.nuv.la

Then, `HNFEDID_URL` `$fed_id_url/auth/realms/$realm_name/.well-known/openid-configuration`

2. Remove `hn-client-id` RTP (`HN_CLIENT_ID=$(ss-get hn-client-id)`) and instead use hardcoded value in `client.json`, e.g. OneZoneClient.

This way DM user needs to provide only KC realm name and access token.

Lets discuss.

**Comment by cjdcordeiro** [comment]
the clientID should be dynamic for use cases where you'll want to have 2 clients on the same realm

**Comment by konstan** [comment]
@cjdcordeiro I think it would be better if we introduce the detection of the default one (OneZoneClient) in KC and editing by adding `rootUrl`s (PUT on client exists according to @elegof).

**Comment by cjdcordeiro** [comment]
@konstan then you'll be assuming that different clients will share the same client-secret and that most importantly, they'll have the same client template. 

Also, for changing the client details, can you use the client registration initial tokens?

**Comment by konstan** [comment]
@cjdcordeiro The script we are working on is for deployment of OneZone only.  There should only be one OneZone per tenant.  So, one KC client for OneZone per tenant is what we want.  However, as one can deploy OneZone in a clustered mode for redundancy, thus there might be multiple instances - this is where I assume we could use KC client "editing" option.

> Also, for changing the client details, can you use the client registration initial tokens?
Good question.  I don't know.  Need to check.

**Comment by cjdcordeiro** [comment]
@konstan I'm not sure there will be just one OneZone per tenant, mostly because of SURFsara's use case. 
Nevertheless, having clientID as an argument with default value is safer

**Comment by konstan** [comment]
I'm not aware of "SURFsara's use case".  What is it about?

Yes, sure. We had this option in mind when discussed this with @elegoff.  We are adjusting the scripts in master now.

**Comment by elegoff** [comment]
Updating client details is possible (http://www.keycloak.org/docs-api/3.1/rest-api/index.html#_clients_resource ) but requires you use access_token (i.e not initial tokens)  but this requires KC credentials.
For the record here is a template I used during my tests to get such access token
```
 TKN=$(curl \
              -d "client_id=admin-cli" \
              -d "username=$KEYCLOAK_USER" \
              -d "password=$KEYCLOAK_PASSWORD" \
              -d "grant_type=password" \
           "https://fed-id.nuv.la/auth/realms/$REALM/protocol/openid-connect | jq -r '.access_token') 
```
which then allow you need to pass
``` 
 -H "Content-Type:application/json" ```
and
```     -H "Authorization: Bearer $TKN"```
```

to your CURL rest API calls as describe here : http://www.keycloak.org/docs-api/3.1/rest-api/index.html#_overview

**Comment by cjdcordeiro** [comment]
@elegoff getting access tokens is a bit trickier.

@konstan SURFsara has the "BBMRi_data" use case and the "dCache_io kubertest". These are independent and apparently they were given different tenancies in OTC, but just one account in Exoscale. So it isn't clear how many tenants should be assigned for them. We'll start with just one tenant in KC and move from there. If they can live with it, then they might have multiple onezone clients to match the different use cases

**Comment by konstan** [comment]
@cjdcordeiro OK. We will expose the parameter and set default to OneZoneClient + will add doc for the RTP.

**Pull request merged**
